site_name: Muntii-Fagarasのドキュメント
site_description: Muntii-Fagarasのドキュメントリポジトリです。
site_author: Muntii-Fagarasチーム
site_url: https://Muntii-Fagaras.github.io/

repo_url: https://github.com/Muntii-Fagaras/Muntii-Fagaras.github.io
repo_name: Muntii-Fagaras/Muntii-Fagaras.github.io

docs_dir: 'docs'

theme: 
  logo: material/city
  name: 'material'
  custom_dir: docs/overrides
  palette:
    primary: blue
    scheme: slate
    accent: cyan
  language: ja
  features:
    - content.code.annotate 
    - codehilite
    - navigation.expand
    - navigation.instant
    - navigation.tracking
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
  icon:
    repo: fontawesome/brands/github 
markdown_extensions:
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
      
nav:
  - このプロジェクトについて: README.md
  - このプロジェクトのビルド方法について: CONTRIBUTING.md
  - 1. ソースコードについて:
    - 1.1. imageについて: description/image.md
    - 1.2. load_fileについて: description/load_file.md
  - このサイトについて: このサイトについて.md
plugins:
  - git-revision-date
  - git-authors
  - tags
  - search:
      lang: ja
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
extra:
  version:
    provider: mike
