site_name: Muntii-Fagarasのドキュメント
site_description: Muntii-Fagarasのドキュメントリポジトリです。
site_author: Muntii-Fagarasチーム
site_url: https://Muntii-Fagaras.github.io/

repo_url: https://github.com/Muntii-Fagaras/Muntii-Fagaras.github.io
repo_name: Muntii-Fagaras/Muntii-Fagaras.github.io

docs_dir: 'docs'

theme: 
  name: 'material'
  custom_dir: docs/overrides
  palette:
    primary: blue
    scheme: slate
    accent: cyan
  language: ja
  features:
    - content.code.annotate 
    - codehilite
    - navigation.expand
    - navigation.instant
    - navigation.tracking
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
  icon:
    repo: fontawesome/brands/github 
markdown_extensions:
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
      
nav:
  - このプロジェクトについて: README.md
  - 1. 実行方法:
      - 1.1. Muntii-Fagarasを実行する方法: instruction/how_to_run/main.md
  - 2. プログラムの使い方:
      - 2.1. メイン画面の操作方法 : instruction/manual/main.md
      - 2.2. 設定画面の操作方法:  instruction/manual/setting.md
plugins:
  - git-revision-date
  - tags
  - with-pdf:
     cover: true
     toc_level: 3
     cover_title: Muntii-Fagaras取扱説明書
  - search:
      lang: ja
markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      use_pygments: true
      linenums: true
      auto_title: true
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
extra:
  version:
    provider: mike
