site_name: Muntii-Fagarasのドキュメント
site_description: Muntii-Fagarasのドキュメントリポジトリです。
site_author: Muntii-Fagarasチーム
site_url: https://Muntii-Fagaras.github.io/

repo_url: https://github.com/Muntii-Fagaras/Muntii-Fagaras.github.io
repo_name: Muntii-Fagaras/Muntii-Fagaras.github.io

docs_dir: 'docs'

theme: 
  name: 'material'
  custom_dir: docs/overrides
  palette:
    primary: blue
    scheme: slate
    accent: cyan
  language: ja
  features:
    - content.code.annotate 
    - codehilite
    - navigation.expand
    - navigation.instant
  icon:
    repo: fontawesome/brands/github 
markdown_extensions:
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
      
nav:
  - このプロジェクトについて: README.md
  - 取扱説明書:
    - 1. インストール方法
      -1.1 WindowsでMuntii-Fagarasを実行する方法 : instructionhow_to_run_windows/main.md
      -1.2 KubuntuでMuntii-Fagarasを実行する方法
      -1.3 React OSでMuntii-Fagarasを実行する方法
    - 2. プログラムの使い方
      - メイン画面の操作方法 : instruction/manual/main.md
      - 設定画面の操作方法
  - このプロジェクトのビルド方法について: CONTRIBUTING.md
    - 1. ソースコードについて:
    - 1.1. imageクラスについて: description/image.md
    - 1.2 load_fileくらすについて: description/load_file.md
  - このサイトについて: このサイトについて.md
plugins:
  - git-revision-date
  - git-authors
  